# Generated by Django 2.1.8 on 2020-05-09 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_auto_20200423_1909'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCaseOfBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
            options={
                'verbose_name': '书架书籍',
                'verbose_name_plural': '书架书籍',
                'db_table': 'bookcase-book',
            },
        ),
        migrations.CreateModel(
            name='UserOfBookCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户书架',
                'verbose_name_plural': '用户书架',
                'db_table': 'user-bookcase',
            },
        ),
        migrations.AddField(
            model_name='bookcaseofbook',
            name='bookcase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookcase.UserOfBookCase'),
        ),
    ]
