# Generated by Django 2.1.8 on 2020-05-11 10:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookcaseofbook',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userofbookcase',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
