# Generated by Django 2.1.8 on 2020-04-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=128, verbose_name='书籍名称')),
                ('author_name', models.CharField(max_length=32, verbose_name='作者')),
                ('is_publish', models.IntegerField(default=1, verbose_name='是否出版')),
                ('status', models.IntegerField(default=1, verbose_name='连载状态')),
                ('cover', models.CharField(max_length=128, verbose_name='封面图片')),
                ('intro', models.TextField(verbose_name='简介')),
                ('showed', models.BooleanField(default=0, verbose_name='是否上架')),
                ('collect_count', models.IntegerField(default=0, verbose_name='被收藏的数量')),
                ('heat', models.IntegerField(default=0, verbose_name='热度')),
            ],
            options={
                'verbose_name': '书籍基本信息',
                'verbose_name_plural': '书籍基本信息',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookBigCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=64, verbose_name='分类名称')),
                ('showed', models.BooleanField(default=1, verbose_name='展示')),
                ('channel', models.IntegerField(default=1, verbose_name='频道')),
                ('icon', models.CharField(max_length=100, verbose_name='图标')),
            ],
            options={
                'verbose_name': '书籍一级分类信息',
                'verbose_name_plural': '书籍一级分类信息',
                'db_table': 'book_big_category',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=64, verbose_name='分类名称')),
                ('showed', models.BooleanField(default='1', verbose_name='展示')),
                ('icon', models.CharField(max_length=100, verbose_name='图标')),
                ('big_category', models.ManyToManyField(to='books.BookBigCategory', verbose_name='大分类')),
            ],
            options={
                'verbose_name': '书籍分类信息',
                'verbose_name_plural': '书籍分类信息',
                'db_table': 'book_category',
            },
        ),
        migrations.CreateModel(
            name='BookChapterContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='章节内容')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='书籍ID')),
            ],
            options={
                'verbose_name': '书籍章节内容信息',
                'verbose_name_plural': '书籍章节内容信息',
                'db_table': 'book_chapter_content',
            },
        ),
        migrations.CreateModel(
            name='BookChapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=64, verbose_name='章节名称')),
                ('word_count', models.IntegerField(verbose_name='字数')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='书籍ID')),
            ],
            options={
                'verbose_name': '书籍章节信息',
                'verbose_name_plural': '书籍章节信息',
                'db_table': 'book_chapters',
            },
        ),
        migrations.AddField(
            model_name='bookchaptercontent',
            name='chapter_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.BookChapters', verbose_name='章节ID'),
        ),
        migrations.AddField(
            model_name='book',
            name='cate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.BookCategory', verbose_name='书籍二级分类ID'),
        ),
        migrations.AddField(
            model_name='book',
            name='channel_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.BookBigCategory', verbose_name='书籍频道'),
        ),
    ]
